# Generated by Django 4.0.4 on 2022-05-12 04:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shoplistapp', '0002_category_meals_category_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meals',
            name='category_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shoplistapp.category'),
        ),
    ]
