# Generated by Django 4.0.4 on 2022-05-20 19:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shoplistapp', '0004_rename_category_categories_meals_servings'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mealsingredients',
            name='meal_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ingredients', to='shoplistapp.meals'),
        ),
        migrations.AlterField(
            model_name='mealsingredients',
            name='unit_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='unit', to='shoplistapp.units'),
        ),
    ]
