# Generated by Django 4.0.4 on 2022-05-21 15:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shoplistapp', '0005_alter_mealsingredients_meal_id_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='meals',
            old_name='category_id',
            new_name='category',
        ),
        migrations.RenameField(
            model_name='mealsingredients',
            old_name='ingredient_id',
            new_name='ingredient',
        ),
        migrations.RenameField(
            model_name='mealsingredients',
            old_name='meal_id',
            new_name='meal',
        ),
        migrations.RenameField(
            model_name='mealsingredients',
            old_name='unit_id',
            new_name='unit',
        ),
    ]
